### ISSUE TITLE
Nothing is installed via `pip install pyasyncore`

### ISSUE THREAD

**Issue by yan12125** [simonrob/pyasyncore#1] opened 2023-06-01 18:28 UTC
`pip install pyasyncore` seems fine:
```
$ python3.12 -m pip install pyasyncore
Collecting pyasyncore
  Downloading pyasyncore-1.0.0-py2.py3-none-any.whl (3.5 kB)
Installing collected packages: pyasyncore
Successfully installed pyasyncore-1.0.0
```
But no Python files are installed to site-packages, and I cannot import asyncore:
```
$ python3.12 -c 'import asyncore'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'asyncore'

$ ls ~/.pyenv/versions/3.12.0b1/lib/python3.12/site-packages
pip  pip-23.1.2.dist-info  pyasyncore-1.0.0.dist-info  README.txt
```
Looks like the wheel file (which I downloaded from https://pypi.org/project/pyasyncore/#files) is missing Python files:
```
$ tar tf pyasyncore-1.0.0-py2.py3-none-any.whl 
pyasyncore-1.0.0.dist-info/LICENSE
pyasyncore-1.0.0.dist-info/METADATA
pyasyncore-1.0.0.dist-info/WHEEL
pyasyncore-1.0.0.dist-info/top_level.txt
pyasyncore-1.0.0.dist-info/RECORD
```
I cannot install from a source distribution, either:
```
$ python3.12 -m pip install --no-binary :all: pyasyncore
Collecting pyasyncore
  Downloading pyasyncore-1.0.0.tar.gz (3.5 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running egg_info
      writing pyasyncore.egg-info/PKG-INFO
      writing dependency_links to pyasyncore.egg-info/dependency_links.txt
      writing top-level names to pyasyncore.egg-info/top_level.txt
      error: package directory 'asyncore' does not exist
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
The source distribution is missing necessary Python files as well:
```
$ tar tf pyasyncore-1.0.0.tar.gz 
pyasyncore-1.0.0/
pyasyncore-1.0.0/LICENSE
pyasyncore-1.0.0/PKG-INFO
pyasyncore-1.0.0/README.md
pyasyncore-1.0.0/pyasyncore.egg-info/
pyasyncore-1.0.0/pyasyncore.egg-info/PKG-INFO
pyasyncore-1.0.0/pyasyncore.egg-info/SOURCES.txt
pyasyncore-1.0.0/pyasyncore.egg-info/dependency_links.txt
pyasyncore-1.0.0/pyasyncore.egg-info/top_level.txt
pyasyncore-1.0.0/setup.cfg
pyasyncore-1.0.0/setup.py
```
In the end, I use `python3.12 -m pip install git+https://github.com/simonrob/pyasyncore` to properly install the library. It will be great if files on PyPI work out-of-box.

By the way, pyasynchat has a similar issue.

**Comment by simonrob** [comment] 2023-06-03 19:39
Thanks for reporting this – it was caused by a misconfiguration when building the wheel, and should now be fixed in [1.0.2](https://pypi.org/project/pyasyncore/). If you can confirm this now works for you via pip I'll update pyasynchat too.

**Comment by yan12125** [comment] 2023-06-04 04:27
Thanks, it works!

**Comment by yan12125** [comment] 2023-06-04 04:31
I noticed new pyasynchat is uploaded as well, and `pip install pyasynchat` now works fine. I think this issue is completely fixed and can be closed?

**Closed as completed** 2023-06-04 06:30 UTC
